server {
    listen 80;
    server_name localhost;

    # 1. Proxy para la API de iTunes
    location /api-itunes/ {
        # Redirige a Apple
        proxy_pass https://itunes.apple.com/;
        proxy_ssl_server_name on;
        
        # Engañamos a Apple
        proxy_set_header User-Agent "curl/7.81.0";
        proxy_set_header Host itunes.apple.com;
        proxy_set_header Origin "";
        proxy_set_header Referer "";

        # Configuración CORS completa
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;

        # Manejo de peticiones preflight (Options) del navegador
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
        }
    }

    # 2. Servir el Frontend compilado (Vite)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Esto es clave para que funcione React Router (redirecciona a index.html si no encuentra la ruta)
        try_files $uri $uri/ /index.html;
    }
}